[package]
name = "simulation"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", features = [
    "wayland",
] }
image = { version = "0.25.4", default-features = false, features = ["png"] }
